// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY36OFEa0K9qo9IHt7X9en6QE2gL0Duyc',
    appId: '1:139692801098:web:74d66387dd8cbbfdfc3ab3',
    messagingSenderId: '139692801098',
    projectId: 'unisoft-tmp',
    authDomain: 'unisoft-tmp.firebaseapp.com',
    databaseURL: 'https://unisoft-tmp-default-rtdb.firebaseio.com',
    storageBucket: 'unisoft-tmp.appspot.com',
    measurementId: 'G-TWFV05974L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmBQavT4adpoEvI3aEAVxDo5cQYbNLvn0',
    appId: '1:139692801098:android:014a1048a54824f3fc3ab3',
    messagingSenderId: '139692801098',
    projectId: 'unisoft-tmp',
    databaseURL: 'https://unisoft-tmp-default-rtdb.firebaseio.com',
    storageBucket: 'unisoft-tmp.appspot.com',
  );
}
