#!/usr/bin/env python3
"""Emits the 20 seed candidates as JSON for tool/seed/seed_candidates.dart.

The people are invented. Everything around them is not: bases, squadrons,
aircraft, ranks, licence authorities and career arcs follow how the PAF and
Pakistani civil aviation actually work, so the seeded pool exercises search,
filtering and matching the way real applicants will.
"""
import json, sys

def base(name, slot, phone, city, dob, links):
    return {
        'full_name': name,
        'email': f'zain{slot}@mail.com',
        'phone': phone,
        'city': city,
        'country': 'Pakistan',
        'date_of_birth': dob,
        'social_links': links,
        'citizenship': ['Pakistan'],
        'work_authorization': ['Citizen — no sponsorship required',
                               'Open to Relocation with Sponsorship'],
        'languages': ['English', 'Urdu'],
        'preferred_regions': ['Middle East', 'South Asia'],
        'employment_type': 'Full-time',
        'willing_relocate': True,
    }

def aircrew(unit, status, notice, extra):
    d = {
        'employer_type': 'Military Branch',
        'military_branch': 'Pakistan Air Force',
        'military_unit': unit,
        'employment_status': status,
        'notice_period': notice,
        'issuing_authority': ['PCAA (Pakistan)', 'Military Authority'],
        'medical_class': 'Class 1',
        'english_proficiency': 'Level 5 (Extended)',
        'violation_history': {'value': False, 'details': ''},
        'accident_history': {'value': False, 'details': ''},
    }
    d.update(extra)
    return d

def maintainer(unit, status, extra):
    d = {
        'employer_type': 'Military Branch',
        'military_branch': 'Pakistan Air Force',
        'military_unit': unit,
        'employment_status': status,
        'cert_authority': ['PCAA (Pakistan)', 'Military Authority'],
        'enforcement_history': {'value': False, 'details': ''},
        'notice_period': '90 Days',
    }
    d.update(extra)
    return d

def generic(position, band, education, extra):
    d = {
        'current_position': position,
        'experience_band': band,
        'background': 'Military',
        'regulators': ['ICAO', 'Other'],
        'notice_period': '1 month',
        'education': education,
        'passport_valid': True,
        'visa_status': 'Pakistani citizen — no sponsorship required in Pakistan',
        'salary_expectation': 42000,
        'safety_training_extra': ['CRM', 'Human Factors', 'SMS', 'First Aid'],
        'memberships': 'Pakistan Aviation Professionals Forum',
    }
    d.update(extra)
    return d

def edu(inst, degree, major, year, grade):
    return {'institutionName': inst, 'degree': degree,
            'majorSubjects': major, 'duration': year, 'marksOrCgpa': grade}

def job(role, org, loc, s, e, duties):
    return {'role': role, 'organization': org, 'location': loc,
            'startDate': s, 'endDate': e, 'duties': duties}

RISALPUR = 'PAF Academy Asghar Khan, Risalpur'
AIRUNI = 'Air University, Islamabad'
CAE = 'College of Aeronautical Engineering, NUST — PAF Academy Risalpur'

P = []

# ── 1. Fighter pilot — F-16 ────────────────────────────────────────────────
P.append(dict(
    slot=1, roleId='fighter_pilot', name='Asfandyar Khattak', city='Islamabad',
    phone='+92 300 4471209', dob='1986-03-14',
    professionalStatus='retired', retirementDate='2024-09-30',
    summary='Squadron Leader (Retd) with 2,150 hours on the F-16 Block 52+, including four years as a Qualified Weapons Instructor at No. 9 Squadron, PAF Base Mushaf. Led composite strike packages during Exercise Indus Shield and stood operational air defence alert through 2019. Now converting to a civil ATPL and targeting a narrowbody seat with a Gulf operator.',
    objectives='Transition to commercial airline flying on the A320 or B737 family and progress to command within five years.',
    skills=['Air Combat Manoeuvring', 'Weapons Delivery', 'Formation Lead', 'Mission Planning', 'CRM Facilitation'],
    awards=['Tamgha-i-Basalat (2019)', 'Chief of Air Staff Commendation (2017)'],
    references=['Air Cdre (Retd) Tariq Mehmood — former OC Flying, PAF Base Mushaf',
                'Wg Cdr Sohail Anjum — Standards & Evaluation, PAF'],
    answers={**base('Asfandyar Khattak', 1, '+92 300 4471209', 'Islamabad', '1986-03-14',
                    ['linkedin.com/in/asfandyar-khattak']),
             **generic('Qualified Weapons Instructor, No. 9 Squadron PAF (Retd)', '10-20 years', 'Master', {
                 'total_hours': 2680, 'pic_hours': 2150, 'sic_hours': 530,
                 'multi_engine_hours': 240, 'turbine_hours': 2680, 'jet_hours': 2680, 'sim_hours': 310,
                 'licenses': ['CPL'],
                 'ratings': ['Instrument', 'Multi-Engine', 'Type Rating', 'Night'],
                 'type_ratings': 'F-16 Block 52+, F-16A/B MLU',
                 'aircraft_flown': 'F-16C/D Block 52+, F-16A/B MLU, K-8 Karakorum, T-37 Tweet',
                 'medical_class': 'Class 1',
                 'crm_training': True, 'human_factors': True, 'dangerous_goods': False,
                 'notice_period': 'Immediate',
                 'awards': 'Tamgha-i-Basalat 2019, Chief of Air Staff Commendation 2017',
                 'salary_expectation': 48000,
             })},
    experience=[
        job('Qualified Weapons Instructor', 'Pakistan Air Force — No. 9 Squadron', 'PAF Base Mushaf, Sargodha', '2020-01', '2024-09',
            'Led air combat and weapons delivery training for 18 operational pilots.\nPlanned and led composite strike packages during Exercise Indus Shield.\nAuthored squadron tactics notes later adopted across the F-16 fleet.'),
        job('Flight Commander', 'Pakistan Air Force — No. 5 Squadron', 'PAF Base Shahbaz, Jacobabad', '2015-06', '2019-12',
            'Flew operational air defence alert and reconnaissance sorties.\nSupervised eight junior pilots through combat readiness workup.'),
    ],
    education=[edu(RISALPUR, 'BSc Aviation Sciences', 'Aviation Sciences', '2008', '3.62 CGPA'),
               edu(AIRUNI, 'MSc Air Power Management', 'Air Power Management', '2021', '3.71 CGPA')],
    certifications=[{'name': 'F-16 Fighter Conversion Course', 'organization': 'Pakistan Air Force'},
                    {'name': 'Qualified Weapons Instructor Course', 'organization': 'PAF CCS Sargodha'},
                    {'name': 'ICAO English Level 5', 'organization': 'PCAA'}],
))

# ── 2. Military pilot — JF-17 Thunder ──────────────────────────────────────
P.append(dict(
    slot=2, roleId='military_pilot', name='Bilal Ahmed Qureshi', city='Rawalpindi',
    phone='+92 321 5538864', dob='1983-11-02',
    professionalStatus='retired', retirementDate='2025-03-31',
    summary='Wing Commander (Retd) and JF-17 Thunder Block II conversion instructor with 3,240 total hours. Ran the type conversion syllabus at No. 16 Squadron, PAF Base Minhas, and served two tours on Mirage III/V before transitioning to the Thunder. Experienced in weapons integration trials with Pakistan Aeronautical Complex.',
    objectives='Secure a type rating instructor or simulator instructor post with a regional operator or defence training provider.',
    skills=['Type Conversion Instruction', 'Weapons Integration Trials', 'Syllabus Design', 'Threat & Error Management'],
    awards=['Sitara-i-Imtiaz (Military) (2022)'],
    publications=['"Beyond Visual Range Engagement Training in a Constrained Airspace", PAF Air Power Review, 2021'],
    references=['Air Cdre (Retd) Junaid Riaz — former Base Commander, PAF Base Minhas'],
    answers={**base('Bilal Ahmed Qureshi', 2, '+92 321 5538864', 'Rawalpindi', '1983-11-02',
                    ['linkedin.com/in/bilal-qureshi-av']),
             **aircrew('No. 16 Squadron "Black Panthers", PAF Base Minhas, Kamra', 'Unemployed / Seeking Role', '30 Days', {
                 'primary_category': ['Fixed-Wing (Airplane)'],
                 'fixed_wing_types': ['JF17', 'Mirage III/V', 'K-8 Karakorum'],
                 'primary_aircraft': 'JF17',
                 'type_ratings': ['JF-17 Block II'],
                 'aircraft_variants': ['JF-17A Block I', 'JF-17B twin-seat'],
                 'license_level': 'Military Rating / Wings',
                 'license_number': 'PAF-GDP-2005-0892',
                 'class_ratings': ['Single-Engine Land (SEL)', 'Instrument Rating (IR)'],
                 'instructor_ratings': ['TRI (Type Rating Instructor)', 'TRE (Type Rating Examiner)'],
                 'medical_expiry': '2026-01-31',
                 'total_hours': 3240, 'pic_hours': 2890, 'sic_hours': 350,
                 'fixed_wing_hours': 3240, 'multi_engine_hours': 180,
                 'turbine_hours': 3240, 'ifr_hours': 520, 'night_hours': 440, 'nvg_hours': 90,
                 'military_profile': ['Tactical / Fighter', 'Training Command'],
                 'security_clearance': 'Top Secret',
                 'landings_day_90': 18, 'landings_night_90': 6, 'last_checkride': '11/2024',
             })},
    experience=[
        job('Officer Commanding — Conversion Flight', 'Pakistan Air Force — No. 16 Squadron', 'PAF Base Minhas, Kamra', '2019-03', '2025-03',
            'Owned the JF-17 type conversion syllabus and checked out 34 pilots onto type.\nFlew weapons integration trial sorties alongside PAC Kamra engineers.\nChaired the squadron flight safety board.'),
        job('Flight Commander', 'Pakistan Air Force — No. 8 Squadron', 'PAF Base Masroor, Karachi', '2012-01', '2019-02',
            'Operated Mirage III/V in the maritime strike role.\nLed the squadron instrument rating standardisation programme.'),
    ],
    education=[edu(RISALPUR, 'BSc Aviation Sciences', 'Aviation Sciences', '2005', '3.48 CGPA'),
               edu('National Defence University, Islamabad', 'MSc War Studies', 'War Studies', '2018', '3.55 CGPA')],
    certifications=[{'name': 'JF-17 Type Conversion Instructor', 'organization': 'Pakistan Air Force'},
                    {'name': 'Flight Safety Officer Course', 'organization': 'PAF Institute of Flight Safety'},
                    {'name': 'ICAO English Level 5', 'organization': 'PCAA'}],
))

# ── 3. Military transport pilot — C-130 ────────────────────────────────────
P.append(dict(
    slot=3, roleId='transport_pilot', name='Hamza Tariq Awan', city='Islamabad',
    phone='+92 333 2214470', dob='1988-07-21',
    professionalStatus='serving', retirementDate='2027-06-30',
    summary='Squadron Leader currently serving on the C-130E/H with No. 6 Squadron at PAF Base Nur Khan. 2,980 hours of heavy transport flying including UN peacekeeping resupply into Africa, domestic flood relief airlift in 2022, and paradrop support to SSG. Holds a current instrument rating and instructs on type.',
    objectives='Move to a civil cargo or humanitarian airlift operator flying the C-130 or a comparable heavy freighter.',
    skills=['Heavy Airlift Operations', 'Tactical Low-Level Navigation', 'Airdrop & Paradrop', 'Load Planning Oversight', 'Disaster Relief Coordination'],
    awards=['UN Peacekeeping Medal (MONUSCO, 2019)', 'Flood Relief Commendation (2022)'],
    references=['Gp Capt Naeem Akhtar — OC Flying Wing, PAF Base Nur Khan'],
    answers={**base('Hamza Tariq Awan', 3, '+92 333 2214470', 'Islamabad', '1988-07-21',
                    ['linkedin.com/in/hamza-t-awan']),
             **generic('Aircraft Commander & Instructor Pilot, No. 6 Squadron PAF', '10-20 years', 'Bachelor', {
                 'total_hours': 2980, 'pic_hours': 1840, 'sic_hours': 1140,
                 'multi_engine_hours': 2860, 'turbine_hours': 2980, 'jet_hours': 0, 'sim_hours': 420,
                 'licenses': ['CPL'],
                 'ratings': ['Instrument', 'Multi-Engine', 'Night', 'Instructor'],
                 'type_ratings': 'C-130E/H, CN-235',
                 'aircraft_flown': 'C-130E, C-130H, CN-235, Cessna 208 Caravan, K-8 Karakorum',
                 'medical_class': 'Class 1',
                 'crm_training': True, 'human_factors': True, 'dangerous_goods': True,
                 'notice_period': '3 months+',
                 'awards': 'UN Peacekeeping Medal (MONUSCO) 2019, Flood Relief Commendation 2022',
                 'salary_expectation': 44000,
             })},
    experience=[
        job('Aircraft Commander & Instructor Pilot', 'Pakistan Air Force — No. 6 Squadron', 'PAF Base Nur Khan, Rawalpindi', '2018-05', '',
            'Commands C-130 crews on strategic airlift, paradrop and casualty evacuation tasks.\nFlew 41 relief sorties into Sindh and southern Punjab during the 2022 floods.\nInstructs new co-pilots through type conversion and line checks.'),
        job('Co-Pilot', 'Pakistan Air Force — No. 21 Squadron', 'PAF Base Chaklala, Rawalpindi', '2012-08', '2018-04',
            'Flew CN-235 and C-130 transport tasks across domestic and UN deployments.'),
    ],
    education=[edu(RISALPUR, 'BSc Aviation Sciences', 'Aviation Sciences', '2010', '3.40 CGPA')],
    certifications=[{'name': 'C-130 Aircraft Commander Upgrade', 'organization': 'Pakistan Air Force'},
                    {'name': 'Dangerous Goods by Air — Category 6', 'organization': 'IATA'},
                    {'name': 'ICAO English Level 5', 'organization': 'PCAA'}],
))

# ── 4. Test pilot ──────────────────────────────────────────────────────────
P.append(dict(
    slot=4, roleId='test_pilot', name='Rizwan Ul Haq', city='Attock',
    phone='+92 300 8890114', dob='1978-05-09',
    professionalStatus='retired', retirementDate='2023-12-31',
    summary='Group Captain (Retd), graduate of the Empire Test Pilots’ School, with 4,100 hours across 14 types. Led production acceptance and post-overhaul test flying at Pakistan Aeronautical Complex Kamra for the JF-17 and Mirage rebuild lines, and ran flight test for the Super Mushshak export programme.',
    objectives='Consult on flight test, certification and acceptance programmes for a manufacturer or civil aviation authority.',
    skills=['Flight Test Engineering', 'Production Acceptance Testing', 'Certification Flight Test', 'Handling Qualities Assessment', 'Test Report Authoring'],
    awards=['Sitara-i-Imtiaz (Military) (2020)', 'PAC Kamra Excellence Award (2016)'],
    publications=['"Post-Overhaul Acceptance Criteria for Legacy Fighter Airframes", Journal of Aeronautical Engineering Pakistan, 2019',
                  '"Spin Recovery Characteristics of the Super Mushshak", ETPS Symposium Proceedings, 2014'],
    references=['Air Vice Marshal (Retd) Kamran Shafi — former Chairman, PAC Kamra'],
    answers={**base('Rizwan Ul Haq', 4, '+92 300 8890114', 'Attock', '1978-05-09',
                    ['linkedin.com/in/rizwan-ul-haq-tp']),
             **generic('Chief Test Pilot (Retd), Pakistan Aeronautical Complex', '20+ years', 'Master', {
                 'total_hours': 4100, 'pic_hours': 3560, 'sic_hours': 540,
                 'multi_engine_hours': 980, 'turbine_hours': 3800, 'jet_hours': 3200, 'sim_hours': 620,
                 'licenses': ['CPL', 'ATPL'],
                 'ratings': ['Instrument', 'Multi-Engine', 'Type Rating', 'Night', 'Instructor'],
                 'type_ratings': 'JF-17, Mirage III/V, F-7PG, K-8, Super Mushshak',
                 'aircraft_flown': 'JF-17 Thunder, Mirage IIIEA/5PA, F-7PG, K-8 Karakorum, Super Mushshak, C-130E, Y-12',
                 'medical_class': 'Class 1',
                 'crm_training': True, 'human_factors': True, 'dangerous_goods': False,
                 'test_school': True,
                 'awards': 'Sitara-i-Imtiaz (Military), PAC Kamra Excellence Award',
                 'notice_period': 'Immediate',
             })},
    experience=[
        job('Chief Test Pilot', 'Pakistan Aeronautical Complex, Kamra', 'Kamra, Attock', '2014-02', '2023-12',
            'Led production acceptance flight test for the JF-17 assembly line.\nRan the Mirage Rebuild Factory post-overhaul test programme.\nOwned flight test for the Super Mushshak export certification campaign.'),
        job('Experimental Test Pilot', 'Pakistan Air Force — Flight Test Wing', 'PAF Base Minhas, Kamra', '2007-06', '2014-01',
            'Flew envelope expansion and stores clearance sorties on Mirage and F-7 airframes.\nAuthored 60+ flight test reports to ETPS reporting standards.'),
    ],
    education=[edu(RISALPUR, 'BSc Aviation Sciences', 'Aviation Sciences', '2000', '3.70 CGPA'),
               edu('Empire Test Pilots’ School, Boscombe Down, UK', 'Postgraduate Diploma in Flight Test', 'Flight Test Engineering', '2007', 'Distinction'),
               edu(AIRUNI, 'MS Aerospace Engineering', 'Aerospace Engineering', '2013', '3.80 CGPA')],
    certifications=[{'name': 'ETPS Fixed-Wing Test Pilot Course', 'organization': 'Empire Test Pilots’ School'},
                    {'name': 'Flight Test Safety Management', 'organization': 'Society of Experimental Test Pilots'}],
))

# ── 5. Helicopter pilot — Mi-17 ────────────────────────────────────────────
P.append(dict(
    slot=5, roleId='helicopter_pilot', name='Ahsan Raza Gilani', city='Peshawar',
    phone='+92 345 9903327', dob='1987-01-30',
    professionalStatus='retired', retirementDate='2025-01-31',
    summary='Squadron Leader (Retd) rotary pilot with 2,410 hours, 1,700 of them on the Mi-17. Flew mountain rescue and casualty evacuation across Gilgit-Baltistan and Chitral, including avalanche response at Siachen, plus VIP transport out of PAF Base Peshawar. Extensive hoist, sling load and NVG experience.',
    objectives='Fly HEMS, offshore or utility rotary operations with a civil operator in Pakistan or the Gulf.',
    skills=['Mountain Flying', 'Hoist & Sling Load', 'NVG Operations', 'Casualty Evacuation', 'Confined Area Landings'],
    awards=['Tamgha-i-Basalat (2020) — Chitral avalanche rescue'],
    references=['Wg Cdr (Retd) Imtiaz Gul — former OC, No. 4 Squadron'],
    answers={**base('Ahsan Raza Gilani', 5, '+92 345 9903327', 'Peshawar', '1987-01-30',
                    ['linkedin.com/in/ahsan-raza-heli']),
             **aircrew('No. 4 Squadron, PAF Base Peshawar', 'Unemployed / Seeking Role', 'Immediate', {
                 'primary_category': ['Rotary-Wing (Helicopter)'],
                 'rotary_types': ['MI17', 'AS350', 'B412'],
                 'primary_aircraft': 'MI17',
                 'type_ratings': ['Mi-17-1V'],
                 'aircraft_variants': ['Mi-17-1V', 'Mi-171', 'Alouette III'],
                 'license_level': 'Military Rating / Wings',
                 'license_number': 'PAF-GDP-2009-1288',
                 'class_ratings': ['Helicopter', 'Instrument Rating (IR)'],
                 'instructor_ratings': ['None'],
                 'medical_expiry': '2026-02-28',
                 'total_hours': 2410, 'pic_hours': 1960, 'sic_hours': 450,
                 'rotary_hours': 2410, 'multi_engine_hours': 1700,
                 'turbine_hours': 2410, 'ifr_hours': 240, 'night_hours': 410, 'nvg_hours': 380,
                 'helicopter_missions': ['HEMS / Air Ambulance', 'Hoist / Sling / External Load', 'VIP / Corporate', 'Mountain Flying'],
                 'military_profile': ['Combat SAR', 'Special Operations'],
                 'security_clearance': 'Secret',
                 'landings_day_90': 34, 'landings_night_90': 14, 'last_checkride': '10/2024',
             })},
    experience=[
        job('Aircraft Captain', 'Pakistan Air Force — No. 4 Squadron', 'PAF Base Peshawar', '2016-04', '2025-01',
            'Captained Mi-17 crews on mountain SAR, casualty evacuation and VIP tasks.\nLed the Chitral avalanche rescue detachment in 2020, recovering 23 casualties.\nMaintained NVG currency and instructed confined-area landing technique.'),
        job('Co-Pilot', 'Pakistan Air Force — No. 41 Squadron', 'PAF Base Chaklala, Rawalpindi', '2011-09', '2016-03',
            'Flew Alouette III and Mi-17 utility and liaison sorties.'),
    ],
    education=[edu(RISALPUR, 'BSc Aviation Sciences', 'Aviation Sciences', '2009', '3.31 CGPA')],
    certifications=[{'name': 'Mi-17 Type Conversion', 'organization': 'Pakistan Air Force'},
                    {'name': 'Mountain Flying & Rescue Course', 'organization': 'PAF Base Skardu Detachment'},
                    {'name': 'ICAO English Level 4', 'organization': 'PCAA'}],
))

# ── 6. Flight instructor ───────────────────────────────────────────────────
P.append(dict(
    slot=6, roleId='flight_instructor', name='Naveed Anwar Sheikh', city='Risalpur',
    phone='+92 301 4472218', dob='1981-09-17',
    professionalStatus='retired', retirementDate='2024-06-30',
    summary='Wing Commander (Retd) and Qualified Flying Instructor with 3,650 hours, of which 2,400 are instructional. Ran basic and advanced flying training at PAF Academy Asghar Khan on the Super Mushshak and K-8 Karakorum, and served as Chief Ground Instructor for two cadet intakes.',
    objectives='Join a civil flight training organisation as a head of training or senior instructor.',
    skills=['Ab-Initio Flight Instruction', 'Instrument Instruction', 'Syllabus Development', 'Student Assessment', 'Upset Prevention & Recovery Training'],
    awards=['Best Flying Instructor Trophy, PAF Academy (2015)'],
    references=['Gp Capt (Retd) Zafar Iqbal — former OC Training Wing, PAF Academy'],
    answers={**base('Naveed Anwar Sheikh', 6, '+92 301 4472218', 'Risalpur', '1981-09-17',
                    ['linkedin.com/in/naveed-anwar-qfi']),
             **aircrew('Primary Flying Training Wing, PAF Academy Asghar Khan, Risalpur', 'Unemployed / Seeking Role', 'Immediate', {
                 'primary_category': ['Fixed-Wing (Airplane)'],
                 'fixed_wing_types': ['Super Mushshak', 'K-8 Karakorum', 'T-37 Tweet', 'C172'],
                 'primary_aircraft': 'K-8 Karakorum',
                 'type_ratings': ['K-8 Karakorum', 'Super Mushshak'],
                 'aircraft_variants': ['MFI-17 Mushshak', 'Super Mushshak'],
                 'license_level': 'Military Rating / Wings',
                 'license_number': 'PAF-GDP-2003-0714',
                 'class_ratings': ['Single-Engine Land (SEL)', 'Multi-Engine Land (MEL)', 'Instrument Rating (IR)'],
                 'instructor_ratings': ['CFI', 'CFII (Instrument)', 'TRI (Type Rating Instructor)'],
                 'medical_expiry': '2025-12-31',
                 'total_hours': 3650, 'pic_hours': 3200, 'sic_hours': 450,
                 'fixed_wing_hours': 3650, 'multi_engine_hours': 620,
                 'turbine_hours': 1900, 'ifr_hours': 880, 'night_hours': 520, 'nvg_hours': 0,
                 'military_profile': ['Training Command'],
                 'security_clearance': 'Confidential',
                 'landings_day_90': 48, 'landings_night_90': 12, 'last_checkride': '05/2024',
             })},
    experience=[
        job('Chief Flying Instructor', 'Pakistan Air Force — PAF Academy Asghar Khan', 'Risalpur, Nowshera', '2017-01', '2024-06',
            'Ran basic and advanced flying training for cadet intakes of 90+ students.\nRewrote the K-8 instrument phase syllabus, cutting failure rates by a third.\nStandardised instructor checks across three training squadrons.'),
        job('Flying Instructor', 'Pakistan Air Force — No. 1 FTS', 'Risalpur, Nowshera', '2009-03', '2016-12',
            'Delivered ab-initio instruction on Mushshak and T-37.\nQualified as Instrument Rating Examiner in 2013.'),
    ],
    education=[edu(RISALPUR, 'BSc Aviation Sciences', 'Aviation Sciences', '2003', '3.55 CGPA'),
               edu(AIRUNI, 'MSc Aviation Management', 'Aviation Management', '2019', '3.60 CGPA')],
    certifications=[{'name': 'Qualified Flying Instructor Course', 'organization': 'Pakistan Air Force'},
                    {'name': 'Instrument Rating Examiner', 'organization': 'Pakistan Air Force'},
                    {'name': 'ICAO English Level 6', 'organization': 'PCAA'}],
))

# ── 7. Air traffic controller ──────────────────────────────────────────────
P.append(dict(
    slot=7, roleId='air_traffic_controller', name='Kashif Mehmood Butt', city='Lahore',
    phone='+92 322 7761140', dob='1985-04-25',
    professionalStatus='retired', retirementDate='2024-11-30',
    summary='Squadron Leader (Retd) air traffic controller with 16 years across PAF tower, approach radar and area control, latterly as Watch Supervisor at Lahore Area Control Centre. Handled mixed military and civil traffic during Exercise Indus Shield and holds current aerodrome and approach radar ratings.',
    objectives='Take up a senior ATC or airspace management role with PCAA or a Gulf air navigation service provider.',
    skills=['Approach Radar Control', 'Area Control', 'Watch Supervision', 'Airspace Coordination', 'Emergency Traffic Handling'],
    awards=['Chief of Air Staff Commendation (2021) — emergency diversion handling'],
    references=['Gp Capt (Retd) Asim Farooq — former Director ATC, PAF'],
    answers={**base('Kashif Mehmood Butt', 7, '+92 322 7761140', 'Lahore', '1985-04-25',
                    ['linkedin.com/in/kashif-mehmood-atc']),
             **generic('Watch Supervisor, Lahore Area Control Centre (Retd)', '10-20 years', 'Bachelor', {
                 'atc_ratings': ['Aerodrome', 'Approach', 'Approach Radar', 'Area', 'Area Radar'],
                 'atc_facility': 'Approach/TRACON',
                 'atc_license_current': True,
                 'radar_endorsement': True,
                 'notice_period': 'Immediate',
                 'awards': 'Chief of Air Staff Commendation, 2021',
             })},
    experience=[
        job('Watch Supervisor — Area Control', 'Pakistan Air Force / PCAA joint civil-military ACC', 'Lahore', '2019-02', '2024-11',
            'Supervised a watch of nine controllers handling upper-airspace traffic over central Punjab.\nCoordinated civil-military airspace release during large-scale exercises.\nLed the unit investigation into three loss-of-separation events and closed all findings.'),
        job('Approach Radar Controller', 'Pakistan Air Force — PAF Base Mushaf', 'Sargodha', '2010-07', '2019-01',
            'Provided radar approach and departure control for fast-jet and transport traffic.\nQualified on-the-job training instructor for trainee controllers.'),
    ],
    education=[edu('Civil Aviation Training Institute, Hyderabad', 'ATC Basic & Rating Courses', 'Air Traffic Control', '2008', 'Distinction'),
               edu('University of the Punjab, Lahore', 'BSc Physics & Mathematics', 'Physics, Mathematics', '2006', '3.20 CGPA')],
    certifications=[{'name': 'Aerodrome & Approach Radar Rating', 'organization': 'PCAA'},
                    {'name': 'ATC On-the-Job Training Instructor', 'organization': 'PCAA'},
                    {'name': 'ICAO English Level 5', 'organization': 'PCAA'}],
))

# ── 8. Avionics engineer ───────────────────────────────────────────────────
P.append(dict(
    slot=8, roleId='avionics_engineer', name='Muhammad Imran Aslam', city='Kamra',
    phone='+92 336 5540912', dob='1984-12-06',
    professionalStatus='serving', retirementDate='2028-04-30',
    summary='Chief Technician (Avionics) with 17 years on fighter avionics and mission systems, currently at the Aircraft Rebuild Factory, PAC Kamra. Specialises in radar and glass-cockpit integration on the JF-17 and Mirage ROSE upgrade, including wire harness fabrication and post-modification functional testing.',
    objectives='Move into a civil avionics certifying-staff role with an MRO, or a defence systems integration post.',
    skills=['Radar & Sensor Systems', 'Wire Harness Fabrication', 'Glass Cockpit Integration', 'Fault Diagnosis', 'Functional Test Procedures'],
    references=['Sqn Ldr Ahmed Waqas — Avionics Officer, Aircraft Rebuild Factory, PAC Kamra'],
    answers={**base('Muhammad Imran Aslam', 8, '+92 336 5540912', 'Kamra', '1984-12-06',
                    ['linkedin.com/in/imran-aslam-avionics']),
             **maintainer('Aircraft Rebuild Factory, Pakistan Aeronautical Complex, Kamra', 'Active Duty', {
                 'primary_trade': ['Avionics & Electrical', 'Armament / Weapons Systems', 'Airframe'],
                 'avionics_skills': ['Navigation Systems', 'Radar & Sensor Systems', 'Flight Deck / Glass Cockpit', 'Wiring / Wire Harness Fabrication', 'Auto-Flight / Autopilot'],
                 'armament_skills': ['Missile Launch Rails', 'Bomb Racks / Stores Management', 'Ejection Seat / Escape Systems'],
                 'airframe_systems': ['Flight Controls', 'Environmental Control Systems (ECS)'],
                 'military_moc': 'PAF Avionics Trade — Radar & Navigation Fitter',
                 'license_number': 'PAF-AVN-2007-4471',
                 'license_expiry': '2027-06-30',
                 'fixed_wing_maintained': ['JF17', 'Mirage III/V', 'F-7PG', 'K-8 Karakorum'],
                 'engine_models': ['RD-93', 'SNECMA Atar 9C'],
                 'maintenance_environment': ['Base / Heavy Maintenance', 'Component / Backshop', 'Flight Line (Military)'],
                 'factory_courses': ['CATIC JF-17 Avionics Gen-Fam', 'Thales ROSE Radar Maintenance'],
                 'total_experience_years': 17,
                 'trade_experience_years': 17,
                 'toolbox_status': 'Has Own Shadowed/Etched Mechanics Toolkit',
                 'security_clearance': 'Secret',
             })},
    experience=[
        job('Chief Technician — Avionics', 'Pakistan Aeronautical Complex, Aircraft Rebuild Factory', 'Kamra, Attock', '2016-03', '',
            'Leads a six-technician avionics bay through JF-17 radar and mission computer installation.\nFabricates and certifies wire harnesses to drawing and inspects to RII standard.\nWrote the functional test card set now used across the Mirage ROSE line.'),
        job('Senior Technician — Radar & Navigation', 'Pakistan Air Force — No. 15 Squadron', 'PAF Base Rafiqui, Shorkot', '2008-01', '2016-02',
            'Maintained radar, IFF and navigation systems on the flight line.\nCleared aircraft for operational sorties under a 45-minute turnaround.'),
    ],
    education=[edu('PAF College of Aeronautical Engineering, Risalpur', 'Diploma in Avionics Technology', 'Avionics', '2007', 'A Grade'),
               edu(AIRUNI, 'BSc Electrical Engineering Technology', 'Electrical Engineering Technology', '2020', '3.35 CGPA')],
    certifications=[{'name': 'JF-17 Avionics General Familiarisation', 'organization': 'CATIC / PAC Kamra'},
                    {'name': 'Aircraft Wiring & Harness Certification', 'organization': 'Pakistan Air Force'},
                    {'name': 'Human Factors in Aircraft Maintenance', 'organization': 'PCAA'}],
))

# ── 9. Aircraft mechanic ───────────────────────────────────────────────────
P.append(dict(
    slot=9, roleId='aircraft_mechanic', name='Abdul Rehman Baloch', city='Quetta',
    phone='+92 314 6620875', dob='1990-08-11',
    professionalStatus='serving', retirementDate='2030-08-31',
    summary='Senior Technician (Airframe & Powerplant) with 12 years on the C-130 and CN-235 fleet at PAF Base Samungli. Runs line maintenance turnarounds, engine change teams and pre-flight servicing, and holds run-up and taxi authorisation on both types.',
    objectives='Qualify as PCAA Part-66 B1.1 certifying staff and join a commercial line maintenance organisation.',
    skills=['Line Maintenance', 'Engine Change', 'Turboprop Systems', 'Hydraulics & Landing Gear', 'Ground Run & Taxi'],
    references=['Sqn Ldr Muhammad Yasir — Engineering Officer, PAF Base Samungli'],
    answers={**base('Abdul Rehman Baloch', 9, '+92 314 6620875', 'Quetta', '1990-08-11', []),
             **maintainer('No. 21 Squadron Engineering Flight, PAF Base Samungli, Quetta', 'Active Duty', {
                 'primary_trade': ['Airframe', 'Powerplant / Engine'],
                 'airframe_systems': ['Landing Gear', 'Flight Controls', 'Fuel Systems', 'Hydraulics', 'Pneumatics'],
                 'powerplant_skills': ['Turboprop', 'APU (Auxiliary Power Unit)'],
                 'military_moc': 'PAF Airframe & Engine Trade — Aircraft Fitter',
                 'license_number': 'PAF-AEF-2012-6620',
                 'license_expiry': '2028-03-31',
                 'fixed_wing_maintained': ['C130', 'CN-235', 'Y-12'],
                 'engine_models': ['Allison T56-A-15', 'GE CT7-9C'],
                 'maintenance_environment': ['Line Maintenance', 'Flight Line (Military)'],
                 'factory_courses': ['Rolls-Royce T56 Line Maintenance'],
                 'total_experience_years': 12,
                 'trade_experience_years': 12,
                 'toolbox_status': 'Has Own Shadowed/Etched Mechanics Toolkit',
                 'security_clearance': 'Confidential',
             })},
    experience=[
        job('Senior Technician — Airframe & Engines', 'Pakistan Air Force — No. 21 Squadron', 'PAF Base Samungli, Quetta', '2017-06', '',
            'Leads a four-technician line crew through C-130 turnarounds and daily inspections.\nCompleted 11 T56 engine changes as team lead with no re-work.\nHolds ground run and taxi authorisation on C-130 and CN-235.'),
        job('Technician — Airframe', 'Pakistan Air Force — No. 6 Squadron', 'PAF Base Nur Khan, Rawalpindi', '2012-09', '2017-05',
            'Carried out scheduled inspections, hydraulic and landing gear servicing.'),
    ],
    education=[edu('PAF School of Aeronautics, Korangi Creek, Karachi', 'Diploma in Aircraft Maintenance Technology', 'Airframe & Powerplant', '2012', 'A Grade')],
    certifications=[{'name': 'C-130 Airframe & Engine Course', 'organization': 'Pakistan Air Force'},
                    {'name': 'T56 Turboprop Line Maintenance', 'organization': 'Rolls-Royce'},
                    {'name': 'Aviation Safety & FOD Prevention', 'organization': 'PAF Institute of Flight Safety'}],
))

# ── 10. Maintenance engineer ───────────────────────────────────────────────
P.append(dict(
    slot=10, roleId='maintenance_engineer', name='Faisal Nadeem Chaudhry', city='Karachi',
    phone='+92 302 3318846', dob='1982-02-19',
    professionalStatus='retired', retirementDate='2024-04-30',
    summary='Squadron Leader (Retd) aeronautical engineer with 18 years of base and depot maintenance leadership, most recently as Officer Commanding Engineering Wing at PAF Base Faisal. Ran the 1,200-hour phase inspection programme for the Mirage fleet and led an ISO 9001 recertification of the base engineering organisation.',
    objectives='Lead a maintenance or continuing airworthiness organisation at a commercial airline or MRO.',
    skills=['Continuing Airworthiness Management', 'Heavy Maintenance Planning', 'Reliability Analysis', 'Quality Systems (ISO 9001)', 'Technical Team Leadership'],
    awards=['Chief of Air Staff Commendation (2018) — fleet availability improvement'],
    publications=['"Reliability-Centred Maintenance on Legacy Fighter Fleets", PAC Kamra Technical Digest, 2020'],
    references=['Air Cdre (Retd) Shahzad Alam — former Director Engineering, PAF'],
    answers={**base('Faisal Nadeem Chaudhry', 10, '+92 302 3318846', 'Karachi', '1982-02-19',
                    ['linkedin.com/in/faisal-nadeem-ame']),
             **maintainer('Engineering Wing, PAF Base Faisal, Karachi', 'Unemployed / Seeking Role', {
                 'primary_trade': ['Airframe', 'Powerplant / Engine', 'Structures / Sheet Metal'],
                 'airframe_systems': ['Landing Gear', 'Flight Controls', 'Fuel Systems', 'Hydraulics', 'Environmental Control Systems (ECS)'],
                 'powerplant_skills': ['Turbofan', 'Turboprop', 'APU (Auxiliary Power Unit)'],
                 'structures_ndt': ['Structural Inspection', 'NDT Level II'],
                 'military_moc': 'PAF Aeronautical Engineering Branch',
                 'license_number': 'PAF-AE-2006-0338',
                 'license_expiry': '2026-12-31',
                 'fixed_wing_maintained': ['Mirage III/V', 'F-7PG', 'C130', 'K-8 Karakorum'],
                 'engine_models': ['SNECMA Atar 9C', 'Allison T56-A-15'],
                 'maintenance_environment': ['Base / Heavy Maintenance', 'Line Maintenance', 'Component / Backshop'],
                 'factory_courses': ['Atar 9C Overhaul', 'ISO 9001:2015 Lead Auditor'],
                 'total_experience_years': 18,
                 'trade_experience_years': 14,
                 'toolbox_status': 'Minimum Toolkit Available',
                 'notice_period': 'Immediate',
                 'security_clearance': 'Secret',
             })},
    experience=[
        job('Officer Commanding — Engineering Wing', 'Pakistan Air Force — PAF Base Faisal', 'Karachi', '2019-01', '2024-04',
            'Led 140 technicians and six engineering officers across line, base and backshop.\nRaised fleet availability from 68% to 84% by rebuilding the phase inspection plan.\nPassed ISO 9001:2015 recertification with zero major findings.'),
        job('Engineering Officer', 'Pakistan Air Force — Mirage Rebuild Factory, PAC Kamra', 'Kamra, Attock', '2010-05', '2018-12',
            'Managed the Atar 9C engine overhaul cell and its spares pipeline.\nIntroduced reliability tracking that cut unscheduled removals by a fifth.'),
    ],
    education=[edu(CAE, 'BE Aerospace Engineering', 'Aerospace Engineering', '2006', '3.58 CGPA'),
               edu('NED University of Engineering & Technology, Karachi', 'MS Mechanical Engineering', 'Mechanical Engineering', '2016', '3.66 CGPA')],
    certifications=[{'name': 'ISO 9001:2015 Lead Auditor', 'organization': 'Bureau Veritas'},
                    {'name': 'Aircraft Maintenance Management Course', 'organization': 'PAF Institute of Aeronautical Engineering'},
                    {'name': 'NDT Level II — Penetrant & Magnetic Particle', 'organization': 'PAC Kamra'}],
))

# ── 11. Structures / composite technician ──────────────────────────────────
P.append(dict(
    slot=11, roleId='structures_technician', name='Zubair Hussain Shah', city='Kamra',
    phone='+92 335 7784023', dob='1989-06-03',
    professionalStatus='serving', retirementDate='2029-06-30',
    summary='Junior Warrant Officer specialising in sheet metal and composite repair at the Aircraft Rebuild Factory, PAC Kamra. Eleven years of structural repair on Mirage and F-7 airframes, including corrosion control, wing spar splice work and carbon fibre patch repair to SRM limits. NDT Level II qualified.',
    objectives='Join a commercial MRO structures bay or a composite repair station in the Gulf.',
    skills=['Sheet Metal Repair', 'Composite Patch Repair', 'Corrosion Control', 'NDT Level II', 'Structural Repair Manual Interpretation'],
    references=['Sqn Ldr Bilal Saeed — Structures Officer, Aircraft Rebuild Factory, PAC Kamra'],
    answers={**base('Zubair Hussain Shah', 11, '+92 335 7784023', 'Kamra', '1989-06-03', []),
             **maintainer('Structures Bay, Aircraft Rebuild Factory, PAC Kamra', 'Active Duty', {
                 'primary_trade': ['Structures / Sheet Metal', 'Airframe'],
                 'structures_ndt': ['Sheet Metal Repair', 'Carbon Fiber / Composite Repair', 'Structural Inspection', 'NDT Level I', 'NDT Level II', 'Eddy Current', 'Ultrasonic'],
                 'airframe_systems': ['Flight Controls'],
                 'military_moc': 'PAF Structures Trade — Airframe Repair Fitter',
                 'license_number': 'PAF-STR-2013-7784',
                 'license_expiry': '2029-01-31',
                 'fixed_wing_maintained': ['Mirage III/V', 'F-7PG', 'JF17'],
                 'maintenance_environment': ['Base / Heavy Maintenance', 'Component / Backshop'],
                 'factory_courses': ['Advanced Composite Repair — PAC Kamra', 'Eddy Current NDT Level II'],
                 'total_experience_years': 11,
                 'trade_experience_years': 11,
                 'toolbox_status': 'Has Own Shadowed/Etched Mechanics Toolkit',
                 'security_clearance': 'Confidential',
             })},
    experience=[
        job('Junior Warrant Officer — Structures', 'Pakistan Aeronautical Complex, Aircraft Rebuild Factory', 'Kamra, Attock', '2018-02', '',
            'Performs structural repair and corrosion control on Mirage and F-7 airframes.\nCompleted a wing spar splice repair that returned a grounded airframe to service.\nInspects composite repairs to NDT Level II before release.'),
        job('Technician — Sheet Metal', 'Pakistan Air Force — No. 25 Squadron', 'PAF Base Bholari, Jamshoro', '2013-04', '2018-01',
            'Carried out skin panel replacement, riveting and battle damage repair.'),
    ],
    education=[edu('PAF School of Aeronautics, Korangi Creek, Karachi', 'Diploma in Aircraft Structures', 'Aircraft Structures', '2013', 'A Grade')],
    certifications=[{'name': 'Advanced Composite Repair', 'organization': 'PAC Kamra'},
                    {'name': 'NDT Level II — Eddy Current & Ultrasonic', 'organization': 'PAC Kamra'},
                    {'name': 'Corrosion Prevention & Control', 'organization': 'Pakistan Air Force'}],
))

# ── 12. Aviation safety officer ────────────────────────────────────────────
P.append(dict(
    slot=12, roleId='safety_officer', name='Adnan Sarwar Malik', city='Islamabad',
    phone='+92 300 5527731', dob='1980-10-12',
    professionalStatus='retired', retirementDate='2024-08-31',
    summary='Wing Commander (Retd) flight safety officer with 15 years in aviation safety, built on 1,900 hours of Mirage flying. Ran flight safety for a fighter wing, introduced flight data monitoring on the JF-17 fleet and led 40+ occurrence investigations. Trained at the PAF Institute of Flight Safety and holds an ICAO SMS Manager certificate.',
    objectives='Head a safety or SMS function at a commercial airline, MRO or civil aviation authority.',
    skills=['Safety Management Systems', 'Flight Data Monitoring', 'Occurrence Investigation', 'Human Factors', 'Just Culture Implementation'],
    awards=['Chief of Air Staff Flight Safety Trophy (2019)'],
    publications=['"Introducing FDM to a Fast-Jet Fleet: Lessons from the JF-17 Programme", PAF Air Power Review, 2022'],
    references=['Air Cdre (Retd) Nadeem Aslam — former Director of Flight Safety, PAF'],
    answers={**base('Adnan Sarwar Malik', 12, '+92 300 5527731', 'Islamabad', '1980-10-12',
                    ['linkedin.com/in/adnan-sarwar-safety']),
             'employer_type': 'Military Service Arm',
             'employer_name': 'Pakistan Air Force',
             'employment_status': 'Unemployed / Seeking Role',
             'notice_period': 'Immediate',
             'enforcement_history': {'value': False, 'details': ''},
             'safety_role': 'Flight Safety Officer (FSO)',
             'safety_background': ['Pilot Background (Fixed-Wing)'],
             'safety_disciplines': ['Safety Management Systems (SMS)', 'Flight Data Monitoring (FDM / FOQA)', 'Aircraft Accident & Incident Investigation', 'Human Factors & CRM'],
             'flight_safety_skills': ['FOQA / FDM Data Analysis', 'Flight Crew Human Factors', 'CRM / TEM Instructor', 'Runway Safety / Incursion Prevention'],
             'sms_skills': ['SMS Development & Rollout (ICAO Doc 9859)', 'Hazard Identification & Risk Assessment (HIRA)', 'Safety Risk Management (SRM)', 'Safety Assurance & Performance Indicators (SPIs / SPTs)', 'Just Culture Implementation'],
             'investigation_methods': ['ICAO Annex 13 Accident Investigation', 'Root Cause Analysis (RCA)', '5 Whys'],
             'safety_credentials': ['ICAO / FAA / EASA SMS Manager Certificate', 'Qualified Aircraft Accident Investigator'],
             'technical_licenses': ['Pilot License (ATPL / CPL / Military Wings)'],
             'issuing_bodies': ['ICAO', 'Military Safety Center'],
             'aviation_sectors': ['Military Aviation (Tactical)', 'Military Aviation (Heavy / Transport)', 'Commercial Airlines (Passenger)'],
             'aircraft_familiarity': ['JF17', 'Mirage III/V', 'C130'],
             'safety_software': ['AQD'],
             'safety_experience_years': 15,
             'operational_experience': 24,
             'erp_roles': ['Crisis Management Team Lead', 'Go-Team / On-Scene Commander'],
             },
    experience=[
        job('Officer Commanding — Flight Safety', 'Pakistan Air Force — Central Air Command', 'PAF Base Mushaf, Sargodha', '2018-06', '2024-08',
            'Ran flight safety across three fighter squadrons and a training wing.\nIntroduced flight data monitoring on the JF-17 fleet and built the SPI dashboard.\nLed 40+ Annex 13 style occurrence investigations to board sign-off.'),
        job('Flight Safety Officer', 'Pakistan Air Force — No. 8 Squadron', 'PAF Base Masroor, Karachi', '2011-01', '2018-05',
            'Ran the squadron hazard reporting scheme and quarterly safety board.\nDelivered CRM and human factors training to aircrew and maintainers.'),
    ],
    education=[edu(RISALPUR, 'BSc Aviation Sciences', 'Aviation Sciences', '2002', '3.44 CGPA'),
               edu('Cranfield University, UK', 'MSc Air Safety Management', 'Air Safety Management', '2017', 'Merit')],
    certifications=[{'name': 'ICAO SMS Manager Certificate', 'organization': 'ICAO'},
                    {'name': 'Aircraft Accident Investigation Course', 'organization': 'Cranfield University'},
                    {'name': 'CRM Instructor', 'organization': 'PAF Institute of Flight Safety'}],
))

# ── 13. Accident investigator ──────────────────────────────────────────────
P.append(dict(
    slot=13, roleId='accident_investigator', name='Shahid Mahmood Janjua', city='Rawalpindi',
    phone='+92 321 4409937', dob='1976-01-28',
    professionalStatus='retired', retirementDate='2023-06-30',
    summary='Group Captain (Retd) and qualified aircraft accident investigator, formerly Director of the PAF Safety Investigation Board. Led or supervised 26 Class A investigations across fighter, transport and rotary fleets, and served as accredited representative on two joint civil-military inquiries with the Safety Investigation Board of Pakistan.',
    objectives='Serve as a lead investigator or safety advisor for a national investigation authority or an airline.',
    skills=['Annex 13 Investigation', 'Wreckage & Site Analysis', 'Flight Data & CVR Analysis', 'Human Factors Analysis', 'Investigation Report Authoring'],
    awards=['Sitara-i-Imtiaz (Military) (2021)'],
    publications=['"Organisational Factors in Fast-Jet Loss of Control Accidents", ISASI Forum, 2020',
                  '"Wreckage Distribution Analysis in Mountainous Terrain", PAF Safety Review, 2018'],
    references=['Air Marshal (Retd) Farhat Hussain — former Deputy Chief of Air Staff (Operations)'],
    answers={**base('Shahid Mahmood Janjua', 13, '+92 321 4409937', 'Rawalpindi', '1976-01-28',
                    ['linkedin.com/in/shahid-janjua-isasi']),
             'employer_type': 'Military Service Arm',
             'employer_name': 'Pakistan Air Force',
             'employment_status': 'Unemployed / Seeking Role',
             'notice_period': 'Immediate',
             'enforcement_history': {'value': False, 'details': ''},
             'safety_role': 'Accident Investigator',
             'safety_background': ['Pilot Background (Fixed-Wing)', 'Pilot Background (Helicopter)'],
             'safety_disciplines': ['Aircraft Accident & Incident Investigation', 'Human Factors & CRM', 'Safety Management Systems (SMS)', 'Flight Data Monitoring (FDM / FOQA)'],
             'flight_safety_skills': ['FOQA / FDM Data Analysis', 'Flight Crew Human Factors'],
             'sms_skills': ['Hazard Identification & Risk Assessment (HIRA)', 'Safety Risk Management (SRM)', 'Just Culture Implementation'],
             'investigation_methods': ['ICAO Annex 13 Accident Investigation', 'Root Cause Analysis (RCA)', 'BowTie Analysis', '5 Whys'],
             'safety_credentials': ['Qualified Aircraft Accident Investigator', 'ICAO / FAA / EASA SMS Manager Certificate'],
             'technical_licenses': ['Pilot License (ATPL / CPL / Military Wings)'],
             'issuing_bodies': ['ICAO', 'Military Safety Center'],
             'aviation_sectors': ['Military Aviation (Tactical)', 'Military Aviation (Rotary)', 'Military Aviation (Heavy / Transport)', 'Commercial Airlines (Passenger)'],
             'aircraft_familiarity': ['F16', 'Mirage III/V', 'C130', 'MI17'],
             'safety_software': ['AQD', 'Q-Pulse'],
             'safety_experience_years': 19,
             'operational_experience': 30,
             'erp_roles': ['Go-Team / On-Scene Commander', 'Crisis Management Team Lead', 'Family Assistance Program Lead'],
             },
    experience=[
        job('Director — Safety Investigation Board', 'Pakistan Air Force — Air Headquarters', 'Islamabad', '2017-04', '2023-06',
            'Directed the PAF accident investigation function across all fleets.\nLed or supervised 26 Class A investigations and their safety recommendations.\nActed as accredited representative on joint inquiries with SIB Pakistan.'),
        job('Senior Investigator', 'Pakistan Air Force — Directorate of Flight Safety', 'Islamabad', '2009-08', '2017-03',
            'Conducted on-site wreckage analysis and flight data recovery.\nBuilt the human factors analysis framework adopted PAF-wide.'),
    ],
    education=[edu(RISALPUR, 'BSc Aviation Sciences', 'Aviation Sciences', '1998', '3.50 CGPA'),
               edu('University of Southern California, Aviation Safety & Security Program', 'Certificate — Aircraft Accident Investigation', 'Aviation Safety', '2012', 'Pass'),
               edu('National Defence University, Islamabad', 'MPhil Strategic Studies', 'Strategic Studies', '2015', '3.72 CGPA')],
    certifications=[{'name': 'Aircraft Accident Investigation — USC ASSP', 'organization': 'University of Southern California'},
                    {'name': 'ISASI Member', 'organization': 'International Society of Air Safety Investigators'},
                    {'name': 'ICAO SMS Manager Certificate', 'organization': 'ICAO'}],
))

# ── 14. SMS manager ────────────────────────────────────────────────────────
P.append(dict(
    slot=14, roleId='sms_manager', name='Umar Farooq Kiani', city='Lahore',
    phone='+92 333 6674408', dob='1984-03-08',
    professionalStatus='retired', retirementDate='2025-02-28',
    summary='Wing Commander (Retd) who built and ran the safety management system for a PAF transport wing, then advised PCAA on SMS acceptance for two domestic operators. Background as an aircraft maintenance engineer, so the risk work is grounded in the hangar as well as the flight deck.',
    objectives='Own the SMS function at an airline or ground handling organisation and take it through regulator acceptance.',
    skills=['SMS Implementation', 'Hazard Identification & Risk Assessment', 'Safety Performance Indicators', 'Internal Audit', 'Regulatory Liaison'],
    awards=['PCAA Safety Partnership Award (2023)'],
    references=['Gp Capt (Retd) Salman Haider — former OC Engineering, PAF Base Nur Khan'],
    answers={**base('Umar Farooq Kiani', 14, '+92 333 6674408', 'Lahore', '1984-03-08',
                    ['linkedin.com/in/umar-farooq-sms']),
             'employer_type': 'Civil Aviation Authority (CAA / FAA)',
             'employer_name': 'Other (Specify)',
             'employment_status': 'Unemployed / Seeking Role',
             'notice_period': '30 Days',
             'enforcement_history': {'value': False, 'details': ''},
             'safety_role': 'Safety Manager (SMS)',
             'safety_background': ['Aircraft Mechanic / Technician (A&P / Part-66)', 'Flight Dispatcher / Operations'],
             'safety_disciplines': ['Safety Management Systems (SMS)', 'Quality Assurance (QA) & Compliance', 'Human Factors & CRM'],
             'maintenance_safety_skills': ['Maintenance Human Factors (MEDA)', 'Tooling & FOD Prevention', 'Airworthiness Risk Assessment', 'Hangars & Ramp Safety'],
             'sms_skills': ['SMS Development & Rollout (ICAO Doc 9859)', 'Hazard Identification & Risk Assessment (HIRA)', 'Safety Risk Management (SRM)', 'Safety Assurance & Performance Indicators (SPIs / SPTs)', 'Just Culture Implementation'],
             'investigation_methods': ['Root Cause Analysis (RCA)', 'BowTie Analysis', '5 Whys', 'IATA Operational Safety Audit (IOSA)'],
             'safety_credentials': ['ICAO / FAA / EASA SMS Manager Certificate', 'NEBOSH International General Certificate (IGC)'],
             'technical_licenses': ['Aircraft Maintenance License (A&P / Part-66 / Military MOS)'],
             'issuing_bodies': ['ICAO', 'Military Safety Center'],
             'aviation_sectors': ['Military Aviation (Heavy / Transport)', 'Commercial Airlines (Passenger)', 'Airport Authorities & Airfield Operations'],
             'aircraft_familiarity': ['C130', 'A320', 'B738'],
             'safety_software': ['Q-Pulse', 'AQD'],
             'safety_experience_years': 12,
             'operational_experience': 20,
             'erp_roles': ['Emergency Command Center Operator', 'Crisis Management Team Lead'],
             },
    experience=[
        job('SMS Advisor', 'Pakistan Civil Aviation Authority — Safety Oversight (secondment)', 'Karachi', '2022-01', '2025-02',
            'Assessed SMS submissions from two domestic operators through to acceptance.\nRan gap analyses against ICAO Doc 9859 and tracked corrective actions.'),
        job('Safety Manager — Air Transport Wing', 'Pakistan Air Force', 'PAF Base Nur Khan, Rawalpindi', '2015-03', '2021-12',
            'Built the wing SMS from scratch, including hazard register and SPI reporting.\nCut ground damage occurrences by 40% over three years.'),
    ],
    education=[edu(CAE, 'BE Aerospace Engineering', 'Aerospace Engineering', '2006', '3.40 CGPA'),
               edu('Lahore University of Management Sciences', 'MBA (Executive)', 'Business Administration', '2020', '3.55 CGPA')],
    certifications=[{'name': 'ICAO SMS Manager Certificate', 'organization': 'ICAO'},
                    {'name': 'NEBOSH International General Certificate', 'organization': 'NEBOSH'},
                    {'name': 'IOSA Auditor Familiarisation', 'organization': 'IATA'}],
))

# ── 15. Flight dispatcher ──────────────────────────────────────────────────
P.append(dict(
    slot=15, roleId='flight_dispatcher', name='Salman Akram Toor', city='Karachi',
    phone='+92 316 8892250', dob='1987-12-14',
    professionalStatus='retired', retirementDate='2024-10-31',
    summary='Squadron Leader (Retd) operations officer turned licensed flight dispatcher, with nine years planning PAF transport missions and three years on the PIA operations control desk. Comfortable with fuel and payload optimisation, ETOPS planning and diversion management across South Asia and the Gulf.',
    objectives='Work an airline operations control desk, progressing to duty manager.',
    skills=['Flight Planning', 'Weight & Balance', 'Fuel Optimisation', 'Meteorological Analysis', 'NOTAM & Route Assessment'],
    references=['Capt. Rehan Sultan — Chief Dispatcher, Pakistan International Airlines'],
    answers={**base('Salman Akram Toor', 15, '+92 316 8892250', 'Karachi', '1987-12-14',
                    ['linkedin.com/in/salman-toor-ops']),
             **generic('Flight Dispatcher, Pakistan International Airlines', '10-20 years', 'Bachelor', {
                 'dispatch_license': True,
                 'ops_systems': 'Lido/Flight, Jeppesen JetPlan, SITA Flight Ops, AIMS',
                 'weather_analysis': True,
                 'weight_balance': True,
                 'notice_period': '2 weeks',
                 'awards': 'PIA Operations Excellence Award, 2023',
             })},
    experience=[
        job('Flight Dispatcher', 'Pakistan International Airlines', 'Karachi', '2021-11', '2024-10',
            'Dispatched up to 22 sectors per shift across the A320 and B777 fleets.\nManaged diversions and fuel re-planning during winter fog operations at Lahore.\nHeld joint responsibility with the commander for flight release.'),
        job('Operations Officer', 'Pakistan Air Force — Air Transport Wing', 'PAF Base Nur Khan, Rawalpindi', '2012-06', '2021-10',
            'Planned strategic airlift and UN deployment missions including diplomatic clearances.\nRan the operations desk for flood relief airlift in 2010 and 2022.'),
    ],
    education=[edu('Institute of Business Management, Karachi', 'BBA Logistics & Supply Chain', 'Logistics', '2011', '3.28 CGPA'),
               edu('Civil Aviation Training Institute, Hyderabad', 'Flight Dispatcher Licence Course', 'Flight Dispatch', '2021', 'Distinction')],
    certifications=[{'name': 'Flight Dispatcher Licence', 'organization': 'PCAA'},
                    {'name': 'Dangerous Goods by Air — Category 10', 'organization': 'IATA'},
                    {'name': 'ETOPS Flight Planning', 'organization': 'Pakistan International Airlines'}],
))

# ── 16. Loadmaster ─────────────────────────────────────────────────────────
P.append(dict(
    slot=16, roleId='loadmaster', name='Tanveer Abbas Bhatti', city='Rawalpindi',
    phone='+92 340 2216693', dob='1986-05-20',
    professionalStatus='serving', retirementDate='2027-05-31',
    summary='Warrant Officer loadmaster on the C-130 with 2,100 flying hours and 14 years of airlift experience. Handles load planning, restraint and airdrop for outsize cargo, vehicles and palletised relief supplies, including UN deployments and the 2022 flood response.',
    objectives='Move to a civil freighter operator as a loadmaster or load control specialist.',
    skills=['Load Planning & Restraint', 'Weight & Balance', 'Airdrop Rigging', 'Dangerous Goods Handling', 'Cargo Loading Supervision'],
    awards=['Flood Relief Commendation (2022)'],
    references=['Sqn Ldr Hamza Tariq Awan — Aircraft Commander, No. 6 Squadron'],
    answers={**base('Tanveer Abbas Bhatti', 16, '+92 340 2216693', 'Rawalpindi', '1986-05-20', []),
             **generic('Loadmaster, No. 6 Squadron, Pakistan Air Force', '10-20 years', 'Diploma', {
                 'ground_functions': ['Ramp', 'Baggage', 'Marshalling'],
                 'gse_licensed': True,
                 'shift_pref': 'Rotating',
                 'dg_awareness': True,
                 'load_planning': True,
                 'notice_period': '3 months+',
                 'awards': 'Flood Relief Commendation, 2022',
                 'salary_expectation': 28000,
             })},
    experience=[
        job('Loadmaster', 'Pakistan Air Force — No. 6 Squadron', 'PAF Base Nur Khan, Rawalpindi', '2014-01', '',
            'Plans and supervises loading for C-130 airlift, airdrop and casualty evacuation.\nRigged and released 60+ container delivery system drops.\nTrained eight junior loadmasters through their operational workup.'),
        job('Air Cargo Handler', 'Pakistan Air Force — Air Movements Section', 'PAF Base Chaklala, Rawalpindi', '2010-03', '2013-12',
            'Handled palletisation, weighing and manifesting for transport tasks.'),
    ],
    education=[edu('PAF School of Aeronautics, Korangi Creek, Karachi', 'Diploma in Air Movements & Logistics', 'Air Movements', '2010', 'B Grade')],
    certifications=[{'name': 'C-130 Loadmaster Course', 'organization': 'Pakistan Air Force'},
                    {'name': 'Dangerous Goods by Air — Category 8', 'organization': 'IATA'},
                    {'name': 'Ground Support Equipment Operator Licence', 'organization': 'Pakistan Air Force'}],
))

# ── 17. UAV pilot ──────────────────────────────────────────────────────────
P.append(dict(
    slot=17, roleId='uav_pilot', name='Danish Iqbal Wattoo', city='Multan',
    phone='+92 313 5548816', dob='1992-02-27',
    professionalStatus='serving', retirementDate='2032-02-28',
    summary='Squadron Leader flying the Burraq and Shahpar II UAS with 1,450 unmanned operating hours. Runs ISR and target acquisition missions in support of ground operations, and qualified as a UAS instructor in 2023. Holds a PCAA remote pilot certificate for civil BVLOS work.',
    objectives='Apply military ISR experience to civil BVLOS survey, inspection or agricultural UAS operations.',
    skills=['ISR Mission Management', 'BVLOS Operations', 'Sensor Payload Operation', 'Mission Planning', 'UAS Instruction'],
    references=['Wg Cdr Arsalan Cheema — OC, No. 40 Squadron (UAS)'],
    answers={**base('Danish Iqbal Wattoo', 17, '+92 313 5548816', 'Multan', '1992-02-27',
                    ['linkedin.com/in/danish-wattoo-uas']),
             **generic('UAS Commander & Instructor, Pakistan Air Force', '5-10 years', 'Bachelor', {
                 'uav_certs': ['BVLOS'],
                 'uav_platforms': 'Burraq, Shahpar II, Bayraktar TB2 (familiarisation), DJI Matrice 300 RTK',
                 'uav_hours': 1450,
                 'notice_period': '3 months+',
                 'salary_expectation': 36000,
             })},
    experience=[
        job('UAS Commander & Instructor', 'Pakistan Air Force — No. 40 Squadron (UAS)', 'PAF Base Rafiqui, Shorkot', '2019-07', '',
            'Commands UAS crews on ISR and target acquisition missions.\nQualified as UAS instructor and wrote the sensor operator syllabus.\nCoordinates airspace deconfliction with civil ATC for training sorties.'),
        job('Sensor Operator', 'Pakistan Air Force — No. 40 Squadron (UAS)', 'PAF Base Rafiqui, Shorkot', '2015-09', '2019-06',
            'Operated EO/IR payloads and produced imagery intelligence products.'),
    ],
    education=[edu(AIRUNI, 'BSc Aerospace Engineering', 'Aerospace Engineering', '2015', '3.44 CGPA')],
    certifications=[{'name': 'UAS Commander Course', 'organization': 'Pakistan Air Force'},
                    {'name': 'Remote Pilot Certificate — BVLOS', 'organization': 'PCAA'},
                    {'name': 'Imagery Intelligence Analysis', 'organization': 'PAF Air Intelligence School'}],
))

# ── 18. QA inspector ───────────────────────────────────────────────────────
P.append(dict(
    slot=18, roleId='qa_inspector', name='Ejaz Ahmed Nasir', city='Kamra',
    phone='+92 331 7702254', dob='1979-07-04',
    professionalStatus='retired', retirementDate='2024-12-31',
    summary='Chief Technician (Retd) turned quality assurance inspector with 21 years across line, base and depot maintenance. Ran the QA cell at the Aircraft Rebuild Factory, PAC Kamra, auditing work packs, tool control and release documentation, and holds borescope and engine inspection authority on the Atar and RD-93.',
    objectives='Take a QA inspector or auditor post with a Part-145 approved maintenance organisation.',
    skills=['Quality Auditing', 'Work Pack Review', 'Borescope Inspection', 'Tool Control', 'Non-Conformance Management'],
    references=['Sqn Ldr (Retd) Faisal Nadeem Chaudhry — former OC Engineering, PAF Base Faisal'],
    answers={**base('Ejaz Ahmed Nasir', 18, '+92 331 7702254', 'Kamra', '1979-07-04',
                    ['linkedin.com/in/ejaz-nasir-qa']),
             **generic('QA Inspector, Aircraft Rebuild Factory, PAC Kamra (Retd)', '20+ years', 'Diploma', {
                 'mx_licenses': ['A&P'],
                 'aircraft_types': 'Mirage III/V, F-7PG, JF-17, K-8 Karakorum, C-130',
                 'engine_types': 'SNECMA Atar 9C, RD-93, Allison T56-A-15',
                 'mx_specialties': ['Airframe', 'Powerplant', 'Structures'],
                 'inspection_authorization': True,
                 'approvals': 'RII Inspector, Engine Borescope Authority, Tool Control Auditor',
                 'borescope': True,
                 'line_maintenance': True,
                 'base_maintenance': True,
                 'sms_experience': True,
                 'safety_domains': ['Quality', 'Compliance', 'Ground Safety'],
                 'auditor_qualified': True,
                 'safety_certs': 'ISO 9001:2015 Internal Auditor, Human Factors in Maintenance',
                 'notice_period': 'Immediate',
             })},
    experience=[
        job('QA Inspector — Depot Maintenance', 'Pakistan Aeronautical Complex, Aircraft Rebuild Factory', 'Kamra, Attock', '2015-01', '2024-12',
            'Audited work packs, tool control and release documentation across the rebuild line.\nHeld engine borescope authority on the Atar 9C and RD-93.\nRaised and closed non-conformance reports with root cause analysis.'),
        job('Senior Technician — Powerplant', 'Pakistan Air Force — No. 15 Squadron', 'PAF Base Rafiqui, Shorkot', '2003-08', '2014-12',
            'Maintained fighter powerplants on the flight line and in the engine bay.'),
    ],
    education=[edu('PAF School of Aeronautics, Korangi Creek, Karachi', 'Diploma in Aircraft Maintenance Technology', 'Airframe & Powerplant', '2003', 'A Grade')],
    certifications=[{'name': 'ISO 9001:2015 Internal Auditor', 'organization': 'Bureau Veritas'},
                    {'name': 'Engine Borescope Inspection Authority', 'organization': 'PAC Kamra'},
                    {'name': 'Human Factors in Aircraft Maintenance', 'organization': 'PCAA'}],
))

# ── 19. Airport operations officer ─────────────────────────────────────────
P.append(dict(
    slot=19, roleId='airport_ops_officer', name='Waqar Younis Malik', city='Islamabad',
    phone='+92 300 7719942', dob='1983-09-30',
    professionalStatus='retired', retirementDate='2025-04-30',
    summary='Squadron Leader (Retd) airfield operations officer with 15 years running movement areas, aerodrome inspections and emergency response at PAF bases, followed by two years on the airside operations desk at Islamabad International. Experienced in runway safety, wildlife hazard management and low-visibility procedures.',
    objectives='Manage airside operations for a commercial airport or ground handling company.',
    skills=['Airside Operations', 'Runway Safety Management', 'Aerodrome Inspection', 'Wildlife Hazard Management', 'Emergency Response Coordination'],
    awards=['PCAA Airside Safety Commendation (2024)'],
    references=['Air Cdre (Retd) Rashid Naeem — former Base Commander, PAF Base Nur Khan'],
    answers={**base('Waqar Younis Malik', 19, '+92 300 7719942', 'Islamabad', '1983-09-30',
                    ['linkedin.com/in/waqar-malik-airside']),
             **generic('Airside Operations Officer, Islamabad International Airport', '10-20 years', 'Bachelor', {
                 'ground_functions': ['Ramp', 'Marshalling', 'Pushback', 'De-icing'],
                 'gse_licensed': True,
                 'shift_pref': 'Rotating',
                 'dg_awareness': True,
                 'notice_period': '1 month',
                 'awards': 'PCAA Airside Safety Commendation, 2024',
             })},
    experience=[
        job('Airside Operations Officer', 'Pakistan Civil Aviation Authority — Islamabad International Airport', 'Islamabad', '2023-05', '2025-04',
            'Ran airside inspections, runway condition reporting and FOD control on shift.\nCoordinated low-visibility procedures through two winter fog seasons.\nChaired the monthly runway safety team meeting.'),
        job('Officer Commanding — Airfield Operations', 'Pakistan Air Force — PAF Base Nur Khan', 'Rawalpindi', '2010-02', '2023-04',
            'Managed movement area operations for mixed military and civil traffic.\nLed the base wildlife hazard management programme.\nDirected the aerodrome emergency exercise cycle.'),
    ],
    education=[edu('Air University, Islamabad', 'BSc Aviation Management', 'Aviation Management', '2009', '3.30 CGPA')],
    certifications=[{'name': 'ICAO Aerodrome Certification & Inspection', 'organization': 'PCAA'},
                    {'name': 'Runway Safety Team Leader', 'organization': 'PCAA'},
                    {'name': 'Airside Driving Permit — All Areas', 'organization': 'PCAA'}],
))

# ── 20. Rescue & fire fighting ─────────────────────────────────────────────
P.append(dict(
    slot=20, roleId='rff_personnel', name='Ghulam Mustafa Sial', city='Faisalabad',
    phone='+92 342 5583370', dob='1988-11-08',
    professionalStatus='serving', retirementDate='2028-11-30',
    summary='Warrant Officer and crash rescue crew commander with 13 years on PAF airfield fire and rescue. Certified on foam tender operations, aircraft extrication and fuel fire suppression, and led the response team during two live aircraft emergencies at PAF Base Rafiqui.',
    objectives='Join a commercial airport rescue and fire fighting service as a watch or crew commander.',
    skills=['Aircraft Rescue & Fire Fighting', 'Foam Tender Operations', 'Aircraft Extrication', 'HazMat Response', 'Crew Command'],
    awards=['Base Commander Commendation (2021) — live aircraft emergency response'],
    references=['Sqn Ldr Kamran Zafar — Officer Commanding, Airfield Services, PAF Base Rafiqui'],
    answers={**base('Ghulam Mustafa Sial', 20, '+92 342 5583370', 'Faisalabad', '1988-11-08', []),
             **generic('Crash Rescue Crew Commander, Pakistan Air Force', '10-20 years', 'Diploma', {
                 'rff_certified': True,
                 'hazmat': True,
                 'notice_period': '3 months+',
                 'awards': 'Base Commander Commendation, 2021',
                 'salary_expectation': 24000,
                 'safety_training_extra': ['First Aid', 'Fire & Smoke', 'Dangerous Goods', 'Human Factors'],
             })},
    experience=[
        job('Crash Rescue Crew Commander', 'Pakistan Air Force — Airfield Services', 'PAF Base Rafiqui, Shorkot', '2018-04', '',
            'Commands a foam tender crew on airfield standby and live emergency response.\nLed the response to two aircraft ground emergencies with no loss of life.\nRuns quarterly extrication and fuel fire drills for the section.'),
        job('Fire Fighter', 'Pakistan Air Force — Airfield Services', 'PAF Base Minhas, Kamra', '2012-01', '2018-03',
            'Crewed rescue and fire fighting vehicles on airfield standby.'),
    ],
    education=[edu('PAF Fire Fighting & Rescue School, Kohat', 'Diploma in Aircraft Rescue & Fire Fighting', 'Fire & Rescue', '2012', 'A Grade')],
    certifications=[{'name': 'ICAO Category 9 ARFF Operations', 'organization': 'PCAA'},
                    {'name': 'HazMat Awareness & Operations', 'organization': 'Pakistan Air Force'},
                    {'name': 'Emergency Medical First Responder', 'organization': 'Rescue 1122 Punjab'}],
))

assert len(P) == 20, f'expected 20 personas, got {len(P)}'
assert {p['slot'] for p in P} == set(range(1, 21))
json.dump(P, sys.stdout, ensure_ascii=False, indent=1)
